let books = [
  {
    titre: "First Wing",
    annee_edition: 1945,
    lien_image: "lien-Image",
    lien_pdf: "lien-Image",
    resume: "Petit résumé du livre",
    editeur: "Rebecca Yarros",
    nombre_de_page: 528,
    category_id: 1,
    writer_id: 1,
  },
  {
    titre: "Second Wing",
    annee_edition: 1947,
    lien_image: "lien-Image",
    lien_pdf: "lien-Image",
    resume: "Petit résumé du livre",
    editeur: "Rebecca Yarros",
    nombre_de_page: 600,
    category_id: 1,
    writer_id: 1,
  },
  {
    titre: "Third Wing",
    annee_edition: 1949,
    lien_image: "lien-Image",
    lien_pdf: "lien-Image",
    resume: "Petit résumé du livre",
    editeur: "Rebecca Yarros",
    nombre_de_page: 455,
    category_id: 1,
    writer_id: 1,
  },
  {
    titre: "Fourth Wing",
    annee_edition: 1951,
    lien_image: "lien-Image",
    lien_pdf: "lien-Image",
    resume: "Petit résumé du livre",
    editeur: "Rebecca Yarros",
    nombre_de_page: 789,
    category_id: 1,
    writer_id: 1,
  },
  {
    titre: "Fifth Wing",
    annee_edition: 1999,
    lien_image: "lien-Image",
    lien_pdf: "lien-Image",
    resume: "Petit résumé du livre",
    editeur: "Rebecca Yarros",
    nombre_de_page: 512,
    category_id: 1,
    writer_id: 1,
  },
];

export { books };
